### ISSUE TITLE
tuple concurrently updated error when granting priviliges on same database for multiple users

### ISSUE THREAD

**Issue by timothegenzmer** [cyrilgdn/terraform-provider-postgresql#223] opened 2022-06-23 08:34 UTC
### Terraform Version
```
Terraform v1.2.3
on darwin_amd64
+ provider registry.terraform.io/cyrilgdn/postgresql v1.16.0
```

### Affected Resource(s)
- postgresql_grant

### Terraform Configuration Files
```hcl
terraform {
  required_version = ">= 1.0"

  required_providers {
    postgresql = {
      source  = "cyrilgdn/postgresql"
      version = ">=1.16"
    }
  }
}

provider "postgresql" {
  port            = 5432
  database        = "postgres"
  username        = "postgres"
  password        = "password"
  sslmode         = "disable"
  superuser = false
}

resource "postgresql_role" "demo" {
  name     = "demo"
  login    = true
  password = "demo"
}

resource "postgresql_role" "demo2" {
  name     = "demo2"
  login    = true
  password = "demo"
}

resource "postgresql_grant" "demo" {
  database    = "postgres"
  role        = postgresql_role.demo.name
  object_type = "database"
  privileges  = ["CONNECT"]
}

resource "postgresql_grant" "demo2" {
  database    = "postgres"
  role        = postgresql_role.demo2.name
  schema      = "public"
  object_type = "database"
  privileges  = ["CONNECT"]
}
```

### Debug Output
https://gist.github.com/timothegenzmer/c918c3d50acae32c83fade871167d283

### Expected Behavior
The provider is able to grant multiple privileges on the same database for multiple users without error

### Actual Behavior
Postgres error that a tuple is updated concurrently
```
╷
│ Error: could not execute revoke query: pq: tuple concurrently updated
│
│   with postgresql_grant.demo,
│   on main.tf line 45, in resource "postgresql_grant" "demo":
│   45: resource "postgresql_grant" "demo" {
│
╵
```

### Steps to Reproduce
1. `terraform apply`

### References
This seems to be similar to 
https://github.com/cyrilgdn/terraform-provider-postgresql/issues/215
https://github.com/cyrilgdn/terraform-provider-postgresql/issues/178
https://github.com/cyrilgdn/terraform-provider-postgresql/pull/169

**Comment by philip-harvey** [comment] 2022-07-07 23:25
This seems to be duplicate of https://github.com/cyrilgdn/terraform-provider-postgresql/issues/178

**Comment by timothegenzmer** [comment] 2022-07-13 09:43
#178 is different in that it is about granting permissions on a schema and a database for the same role.

This issue is about granting permissions on the same database for different roles.
It might be a duplicate nevertheless

**Closed** 2022-11-17 11:31 UTC
