### ISSUE TITLE
postgresq_grant not working when provider has no expected version

### ISSUE THREAD

**Issue by voroniys** [cyrilgdn/terraform-provider-postgresql#38] opened 2021-01-20 15:46 UTC
Hi there,

Thank you for opening an issue. Please provide the following information:

### Terraform Version
Terraform v0.14.3
+ provider registry.terraform.io/cyrilgdn/postgresql v1.11.0
+ provider registry.terraform.io/hashicorp/aws v3.24.1

### Affected Resource(s)
postgresql_grant

### Terraform Configuration Files
```hcl
provider "postgresql" {
  host             = local.pgsql["host"]
  port             = local.pgsql["port"]
  username         = local.pgsql["username"]
  password         = local.pgsql["password"]
  sslmode          = "require"
  connect_timeout  = 15
  superuser        = false
}

resource postgresql_grant "application" {
  database    = postgresql_database.application.name
  role        = postgresql_role.application.name
  object_type = "database"
  privileges  = ["CONNECT", "CREATE", "TEMPORARY"]
  with_grant_option = true
}
```

### Expected Behavior
It should just work without any issues

### Actual Behavior
If provider configuration contains no option `expected_version`  the resource is failing with error message:
Error: postgresql_grant resource is not supported for this Postgres version (0.0.0)

Provider is connected to the DB instance and is able to create another resources, such as databases and roles. 

It looks like validation is done against `expected_version` from provider configuration and not against the actual version provider connected to.

If I set the expected_version option everything is working like it should

### Steps to Reproduce
Create configuration similar to mentioned above and do `terraform apply`

**Comment by cyrilgdn** [comment] 2021-02-02 22:43
Hi @voroniys ,

Thanks for opening this issue (and sorry for the response delay, I missed some notifications from Github :man_facepalming: )

What's the version of your Postgresql server?  Could you provide the result of `SELECT version();` query?

Thanks in advance.

**Comment by cyrilgdn** [comment] 2021-05-21 15:04
I allow myself to close this issue as the author didn't answer and it's probably a duplicate of #49

**Closed by cyrilgdn** 2021-05-21 15:04 UTC
Labels: waiting-response
