### ISSUE TITLE
Easily hit the quota of Google Cloud SQL Admin API

### ISSUE THREAD

**Issue by yu-iskw** [cyrilgdn/terraform-provider-postgresql#163] opened 2021-11-29 06:54 UTC
### Terraform Version
```
Terraform v1.0.9
on darwin_amd64
```

### Affected Resource(s)
whatever resources when we use `gcppostgres`.

### Terraform Configuration Files
```hcl
provider "postgresql" {
  alias     = "terraform"
  scheme    = "gcppostgres"
  host      = "xxx"
  username  = "xxx"
  password  = "xxxx"
  superuser = true
}
```

### Debug Output
```
│ Error: error detecting capabilities: error PostgreSQL version: googleapi: Error 429: Quota exceeded for quota metric 'Queries' and limit 'Queries per minute per user' of service 'sqladmin.googleapis.com' for consumer 'project_number:xxxxxxxxxxxxxx'.
```

### Panic Output
NA

### Expected Behavior
We want to avoid the quota.

### Actual Behavior
The

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create the provider with `gcppostgres`
2. Create some resources with the provider
3. `terraform apply`

### References
- https://cloud.google.com/sql/docs/mysql/connect-admin-proxy#troubleshooting

**Comment by cyrilgdn** [comment] 2022-01-30 22:52
Hi @yu-iskw ,

What are the quota numbers ? How many resources do you manage?
Unless there's a bug in the provider, I don't really know what we can simply do for that. (Implementing a quota management is probably doable but not that simple in current state)

**Comment by cyrilgdn** [comment] 2022-05-04 16:42
Without any answer, and as it's probably not the role of the provider to manage GCP quota, I allow myself to close this issue.
But feel free to open it back if needed.

**Closed by cyrilgdn** 2022-05-04 16:42 UTC

**Comment by kirecek** [comment] 2023-02-02 22:11
Sorry for jumping into such an old issue, but didn't want to open a new one.

Anyways, FTR, this happens when you manage too many resources with this schema.

Google SQL admin API has a rate limit of **180 requests per minute** which is actually not that hard to hit _(10-20 databases with a couple roles&privileges in each db)._

The problem is described also in this issue https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/issues/413 with some recommendations.

However, the postgres provider is not using cloud-sql-go-connector directly, but through 2 other deps (go-cloud->cloudsql-proxy->go-connector)

I think the provider needs to initialize a dialer instead of letting a client always generate it. I'll try to have a look at this.
