### ISSUE TITLE
Feature: Please support better behavior for 'ALL' postgresql_grant

### ISSUE THREAD

**Issue by nneul** [cyrilgdn/terraform-provider-postgresql#174] opened 2022-01-09 17:52 UTC
Please have the module either

A) reject use of 'ALL' 
or
B) make a better effort to translate internally to the list of valid privileges
or at least
C) document that this is expected behavior (won't ever reach stable state) in the provider docs

when using privileges = ["ALL"]

### Terraform Version

```
Terraform v1.1.2
on linux_amd64
+ provider registry.terraform.io/cyrilgdn/postgresql v1.14.0
+ provider registry.terraform.io/datadog/datadog v3.7.0
+ provider registry.terraform.io/hashicorp/aws v3.71.0
+ provider registry.terraform.io/hashicorp/external v2.2.0
+ provider registry.terraform.io/hashicorp/vault v3.1.1

```

### Affected Resource(s)
Please list the resources as a list, for example:
- postgresql_grant

### Expected Behavior
Nothing should happen after first apply

### Actual Behavior
Thinks resource needs to be updated on every run due to pg translating 'ALL' into the individual grants and needing to be updated on every apply. 

If you list out the privileges individually, it behaves as expected.

**Comment by cyrilgdn** [comment] 2022-01-30 21:22
Thanks for opening this issue, I allow myself to close it as it's a duplicate of #32

**Closed by cyrilgdn** 2022-01-30 21:22 UTC
